package quanlynhanvien;



import java.awt.Container;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author phamh
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {

        
        initComponents();
        
        
        this.veLaiFrame(new UIPanelNhanVien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuTongQuan = new javax.swing.JMenu();
        jMenuItemDanhSachNhanVien = new javax.swing.JMenuItem();
        jMenuItemTinhLuong = new javax.swing.JMenuItem();
        jMenuHangHoa = new javax.swing.JMenu();
        jMenuItemThietLapGia = new javax.swing.JMenuItem();
        jMenuGiaoDich = new javax.swing.JMenu();
        jMenuDoiTac = new javax.swing.JMenu();
        jMenuBaoCao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 50));

        jPanelContent.setLayout(new java.awt.CardLayout());

        jMenuBar.setPreferredSize(new java.awt.Dimension(326, 25));

        jMenuTongQuan.setBorder(null);
        jMenuTongQuan.setText("Nhân viên");
        jMenuTongQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTongQuanActionPerformed(evt);
            }
        });

        jMenuItemDanhSachNhanVien.setText("Danh sách nhân viên");
        jMenuItemDanhSachNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDanhSachNhanVienActionPerformed(evt);
            }
        });
        jMenuTongQuan.add(jMenuItemDanhSachNhanVien);

        jMenuItemTinhLuong.setText("Xem lương");
        jMenuItemTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTinhLuongActionPerformed(evt);
            }
        });
        jMenuTongQuan.add(jMenuItemTinhLuong);

        jMenuBar.add(jMenuTongQuan);

        jMenuHangHoa.setText("Phòng Ban");
        jMenuHangHoa.setMinimumSize(new java.awt.Dimension(100, 19));

        jMenuItemThietLapGia.setText("Thiết lập giá");
        jMenuItemThietLapGia.setActionCommand("");
        jMenuItemThietLapGia.setPreferredSize(new java.awt.Dimension(100, 22));
        jMenuItemThietLapGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThietLapGiaActionPerformed(evt);
            }
        });
        jMenuHangHoa.add(jMenuItemThietLapGia);

        jMenuBar.add(jMenuHangHoa);

        jMenuGiaoDich.setText("Chức vụ");
        jMenuBar.add(jMenuGiaoDich);

        jMenuDoiTac.setText("Lương");
        jMenuBar.add(jMenuDoiTac);

        jMenuBaoCao.setText("Tra cứu");
        jMenuBar.add(jMenuBaoCao);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemThietLapGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThietLapGiaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItemThietLapGiaActionPerformed

    private void jMenuTongQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTongQuanActionPerformed
        

        
        
    }//GEN-LAST:event_jMenuTongQuanActionPerformed

    private void jMenuItemTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTinhLuongActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuItemTinhLuongActionPerformed

    private void jMenuItemDanhSachNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDanhSachNhanVienActionPerformed
        // TODO add your handling code here:
        this.veLaiFrame(new UIPanelNhanVien());
    }//GEN-LAST:event_jMenuItemDanhSachNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    private void veLaiFrame(JComponent component){
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();

        //ve panel danh muc
        jPanelContent.add(component);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuBaoCao;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDoiTac;
    private javax.swing.JMenu jMenuGiaoDich;
    private javax.swing.JMenu jMenuHangHoa;
    private javax.swing.JMenuItem jMenuItemDanhSachNhanVien;
    private javax.swing.JMenuItem jMenuItemThietLapGia;
    private javax.swing.JMenuItem jMenuItemTinhLuong;
    private javax.swing.JMenu jMenuTongQuan;
    private javax.swing.JPanel jPanelContent;
    // End of variables declaration//GEN-END:variables
}
